"use client";

import { useState } from "react";
import { 
  Copy, 
  Check, 
  GitPullRequest, 
  X
} from "lucide-react";
import type { Redline } from "@/lib/schemas/analysis";

interface RedlinePanelProps {
  concernTitle: string;
  originalQuote: string;
  redline?: Redline;
  onClose?: () => void;
}

export function RedlinePanel({
  concernTitle,
  originalQuote,
  redline,
  onClose,
}: RedlinePanelProps) {
  const [selectedTone, setSelectedTone] = useState<"gentle" | "standard" | "firm">("standard");
  const [copiedType, setCopiedType] = useState<"redline" | "email" | null>(null);

  // Fallback if redline was not yet generated by the pipeline for this record
  const effectiveReplacement =
    redline?.suggested_replacement ??
    `Notwithstanding anything to the contrary, ${originalQuote.replace(/shall not/gi, "shall not unreasonably")}; provided that this provision shall strictly apply only during active engagement and exclude pre-existing intellectual property and personal non-commercial projects.`;

  const effectiveDiff =
    redline?.strikethrough_diff ??
    originalQuote.replace(
      /(twenty-four \(24\) months|globally|all competitive enterprises|indefinitely|unlimited)/gi,
      (match) => `~~${match}~~ **[standard mutual limitation]**`
    );

  const effectiveRationale =
    redline?.rationale ??
    "Rebalances unilateral risk to align with standard commercial and employment market precedents.";

  const effectiveEmail =
    redline?.negotiation_drafts?.[selectedTone] ??
    (selectedTone === "gentle"
      ? `Hi team,\n\nI am really excited about moving forward with this agreement! While reviewing the details, I noticed the language in Section regarding "${concernTitle}".\n\nTo ensure mutual alignment, would it be possible to adjust this section to the following wording?\n\n"${effectiveReplacement}"\n\nLooking forward to finalizing things together!`
      : selectedTone === "firm"
        ? `Dear team,\n\nUpon legal review of the agreement, the provision regarding "${concernTitle}" presents an unacceptable liability allocation that deviates significantly from market standards.\n\nWe require the clause to be amended as follows prior to execution:\n\n"${effectiveReplacement}"\n\nPlease update the draft and send over an updated revision for signature.`
        : `Hi team,\n\nThank you for sharing the draft agreement. Overall, the terms look straightforward, but we have a standard request regarding "${concernTitle}".\n\nTo reflect standard industry practice, we propose updating the clause to:\n\n"${effectiveReplacement}"\n\nPlease let us know if this works so we can execute the agreement. Thank you!`);

  const handleCopy = (text: string, type: "redline" | "email") => {
    navigator.clipboard.writeText(text);
    setCopiedType(type);
    setTimeout(() => {
      setCopiedType(null);
    }, 2000);
  };

  return (
    <div className="rounded-xl border border-[#D8D2C6] bg-[#FFFDF7] p-5 shadow-sm space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-[#D8D2C6] pb-3">
        <div className="flex items-center gap-2">
          <span className="flex h-7 w-7 items-center justify-center rounded-[6px] bg-[#F04D35]/10 text-[#F04D35]">
            <GitPullRequest className="h-4 w-4" />
          </span>
          <div>
            <h4 className="font-['Georgia',serif] text-base font-semibold text-[#171714]">
              Counter-Proposal & Redline Desk
            </h4>
            <p className="text-[11px] text-[#646158] font-mono">
              TARGET: {concernTitle}
            </p>
          </div>
        </div>
        {onClose && (
          <button
            type="button"
            onClick={onClose}
            className="rounded-[4px] p-1 text-[#646158] hover:text-[#171714] hover:bg-[#F3F0E8] transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        )}
      </div>

      {/* Visual Redline Strikethrough Diff */}
      <div>
        <div className="flex items-center justify-between mb-1.5">
          <span className="font-mono text-[10px] font-bold uppercase tracking-wider text-[#646158]">
            Visual Redline (Track Changes)
          </span>
          <button
            type="button"
            onClick={() => handleCopy(effectiveReplacement, "redline")}
            className="inline-flex items-center gap-1 font-mono text-[11px] font-semibold text-[#3157D5] hover:underline"
          >
            {copiedType === "redline" ? (
              <>
                <Check className="h-3 w-3 text-[#2E7D4F]" />
                <span className="text-[#2E7D4F]">Copied Clause</span>
              </>
            ) : (
              <>
                <Copy className="h-3 w-3" />
                <span>Copy Replacement</span>
              </>
            )}
          </button>
        </div>

        <div className="rounded-[6px] border border-[#D8D2C6] bg-[#F3F0E8]/50 p-3.5 text-[13px] leading-relaxed font-['Georgia',serif]">
          <FormattedDiff text={effectiveDiff} />
        </div>
        <p className="mt-1 text-[11px] text-[#646158]">
          <strong className="text-[#171714]">Rationale:</strong> {effectiveRationale}
        </p>
      </div>

      {/* Tone Selector & Negotiation Email */}
      <div className="border-t border-[#D8D2C6] pt-3.5 space-y-2.5">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <span className="font-mono text-[10px] font-bold uppercase tracking-wider text-[#646158]">
            Negotiation Email Draft
          </span>

          {/* Tone Selector Pills */}
          <div className="inline-flex rounded-[6px] border border-[#D8D2C6] bg-[#F3F0E8] p-0.5 text-[11px] font-mono">
            <button
              type="button"
              onClick={() => setSelectedTone("gentle")}
              className={`px-2.5 py-1 rounded-[4px] font-medium transition-all ${
                selectedTone === "gentle"
                  ? "bg-[#FFFDF7] text-[#171714] font-bold shadow-2xs"
                  : "text-[#646158] hover:text-[#171714]"
              }`}
            >
              🕊️ Gentle
            </button>
            <button
              type="button"
              onClick={() => setSelectedTone("standard")}
              className={`px-2.5 py-1 rounded-[4px] font-medium transition-all ${
                selectedTone === "standard"
                  ? "bg-[#FFFDF7] text-[#171714] font-bold shadow-2xs"
                  : "text-[#646158] hover:text-[#171714]"
              }`}
            >
              ⚖️ Standard
            </button>
            <button
              type="button"
              onClick={() => setSelectedTone("firm")}
              className={`px-2.5 py-1 rounded-[4px] font-medium transition-all ${
                selectedTone === "firm"
                  ? "bg-[#FFFDF7] text-[#171714] font-bold shadow-2xs"
                  : "text-[#646158] hover:text-[#171714]"
              }`}
            >
              🛡️ Firm
            </button>
          </div>
        </div>

        {/* Generated Email Preview Box */}
        <div className="relative rounded-[6px] border border-[#D8D2C6] bg-[#FFFDF7] p-3.5 text-[12px] text-[#171714] leading-relaxed whitespace-pre-line font-mono">
          {effectiveEmail}
        </div>

        {/* Copy Email Button */}
        <div className="flex justify-end">
          <button
            type="button"
            onClick={() => handleCopy(effectiveEmail, "email")}
            className="inline-flex items-center gap-1.5 rounded-[6px] bg-[#F04D35] px-4 py-2 text-[12px] font-bold text-[#FFFDF7] transition-all hover:bg-[#C93625] active:scale-[0.96] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#3157D5]"
          >
            {copiedType === "email" ? (
              <>
                <Check className="h-3.5 w-3.5" />
                <span>Copied Email to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                <span>Copy Ready-to-Send Email</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

/** Formats markdown diff like ~~deleted~~ in red strikethrough and **added** in green bold */
function FormattedDiff({ text }: { text: string }) {
  // Simple token regex splitting on ~~deleted~~ and **added**
  const parts = text.split(/(~~.*?~~|\*\*.*?\*\*)/g);

  return (
    <span>
      {parts.map((part, index) => {
        if (part.startsWith("~~") && part.endsWith("~~")) {
          const content = part.slice(2, -2);
          return (
            <del
              key={index}
              className="bg-[#C53B36]/15 text-[#C53B36] line-through px-1 py-0.5 rounded-[3px] mx-0.5"
            >
              {content}
            </del>
          );
        }
        if (part.startsWith("**") && part.endsWith("**")) {
          const content = part.slice(2, -2);
          return (
            <ins
              key={index}
              className="bg-[#2E7D4F]/15 text-[#2E7D4F] no-underline font-bold px-1 py-0.5 rounded-[3px] mx-0.5"
            >
              {content}
            </ins>
          );
        }
        return <span key={index}>{part}</span>;
      })}
    </span>
  );
}
